server:
  port: 8080

spring:
  application:
    name: FtsApp
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: "jdbc:postgresql://localhost:5432/shard_db"
    username: postgres
    password: postgres

  autoconfigure:
    exclude: "org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration"

  liquibase:
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    change-log: classpath:liquibase/db.changelog-master.yaml
    default-schema: public

minio:
  endpoint: ${MINIO_ENDPOINT}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}
  bucketName: ${MINIO_BUCKET_NAME}

jwt:
  secret: "b03b690b4c1317d77084236c319ae315856cd86be82e35a3aea75a2d2d07b2a3c6a2fea880ecb549475d19fe80d2f8a4334f77137dab708f60b72cf0ec7070d5"


