server:
  port: ${SERVICE_PORT}

spring:
  application:
    name: FtsApp
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: "jdbc:postgresql://${FTS_APP_DB_IP}:${FTS_APP_DB_PORT}/${FTS_APP_DB_NAME}"
    username: ${FTS_APP_DB_USER}
    password: ${FTS_APP_DB_PASSWORD}

  autoconfigure:
    exclude: "org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration"

  liquibase:
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    change-log: classpath:liquibase/db.changelog-master.yaml
    default-schema: public

minio:
  endpoint: ${MINIO_ENDPOINT}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}
  bucketName: ${MINIO_BUCKET_NAME}

jwt:
  secret: ${JWT_SECRET}


